# Generated by Django 4.1.7 on 2023-06-01 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_files_delete_weatherprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 13, 37, 50, 146294, tzinfo=datetime.timezone.utc)),
        ),
    ]
