# Generated by Django 4.1.7 on 2023-06-01 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_files_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='photo',
            new_name='files',
        ),
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 22, 18, 42, 510721, tzinfo=datetime.timezone.utc)),
        ),
    ]
