# Generated by Django 4.1.7 on 2023-06-01 22:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_files_date_alter_files_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 22, 41, 36, 817406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'word', 'excel'])]),
        ),
    ]
